version: "3"

services:
    mysql:
        image: mysql:5.5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - mysql_data_3307:/var/lib/mysql
    tomcat:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8081:8080"
            - "8444:8443"
        volumes:
            - maven_repository:/root/.m2/repository
            - ./project:/project
            - ./docker/entrypoint/start-tomcat.sh:/entrypoint/start-tomcat.sh
            - ./docker/entrypoint/monitor-event.sh:/entrypoint/monitor-event.sh
            - ./docker/entrypoint/write-event.sh:/entrypoint/write-event.sh
            - ./docker/entrypoint/handle-event.sh:/entrypoint/handle-event.sh
            - /tmp/fpc_docker_tmp/:/tmp/
volumes:
    mysql_data_3307:
        driver: local
    maven_repository:
        driver: local
