#!/bin/bash
# "Starting in MongoDB 4.0, you cannot specify --nojournal option or
# storage.journal.enabled:false for replica set members that use the WiredTiger storage engine.
main() {
  local node=$1
  local hop=$2
  local replset_name=$3
  local pri=$4
  local pop="Node: ${node}\nsshhop: ${hop}\nReplset name: $replset_name\nPrimary IP: $pri"
  confirm_or_exit "$pop"

  local hu=ubuntu
  local nu=ec2-user
  local f="conf_install_mongod.sh"

  scp -o ProxyCommand="ssh -W %h:%p ${hu}@${hop}" ./$f ${nu}@${node}:/tmp/
  ssh ${hu}@$hop ssh ${nu}@$node "bash /tmp/$f $replset_name"

  # Current config
  show_replset_config @{hu} ${hop} ${nu} ${pri}
  pop="Check: No Arbiter in this replset}"
  confirm_or_exit "$pop"
  # Add Arbiter

  local host=$(@{hu}@$hop ssh ${nu}@$node hostname)
  echo "mongo --eval \"rs.status().members.forEach(function(m){
    printjson(m.name + ' : ' + m.stateStr)
});   \"" | ssh -t ${hu}@$hop ssh ${nu}@$pri | grep $host
  if [[ $? == 0 ]]; then
    echo "The current node $host has been in the replset" >&2
  else
    echo "mongo --eval \"rs.addArb('$host')\"" | ssh -t ${hu}@$hop ssh ${nu}@$pri
  fi

  # Check status
  show_replset_status @{hu} ${hop} ${nu} ${pri}
  # Check config
  show_replset_config @{hu} ${hop} ${nu} ${pri}
  # DB, collections, documents number.
  replset_info_db_coll_docu_number ${node} ${hu} $hop ${nu}
}

if [[ -z "$@" ]]; then
  echo -e "Call this bash file like\n ./$0 node_IP sshopIP replset-name primaryIP"
  exit 1
fi
. ./common.sh
main "$@"
