#!/bin/bash
source ./common.sh
main() {
  # $@ is not array
  local input=("$@")
  local hop=${input[-2]}
  local nodes=("${input[@]:0:$#-2}")
  #${!#}
  local replset_name="${@: -1}"
  local pop="
  Nodes: ${nodes[@]}
  sshhop: ${hop}
  Replset name: $replset_name"
  confirm_or_exit "$pop"

  local hu="${sshhop_user_name}"
  local nu="${ec2_user_name}"

  local install_f="conf_install_mongod.sh"
  for f in "${install_f}" "common.sh" "./common_replsets_nodes_ip.sh"; do
    scp -o ConnectTimeout=10 -o ProxyCommand="ssh -W %h:%p ${hu}@${hop}" ./$f ${nu}@${node}:/tmp/
  done
  echo "cd /tmp; ./$install_f" | ssh ${hu}@$hop ssh -o StrictHostKeyChecking=no ${nu}@$node

  # Select one as primary

  local pri=${nodes[0]}
  local secs=${nodes[@]:1}

  # replset initiate
  local pop="Sure the replset is not initialized"
  confirm_or_exit "$pop"
  local js="\"rs.initiate()\""
  mongo_eval "${js}" "${hu}" "${hop}" "${nu}" "${pri}"

  # Current config
  show_replset_config "${hu}" "${hop}" "${nu}" "${pri}"
  local pop="Sure only one member in replset"
  confirm_or_exit "$pop"
  # Set higher priority to make it as a permanent primary
  local note="Note: reconfig need restart mongod.  This may be a bug of 3.6"
  echo -e "\n\n =============$note=============== \n\n"
  # TODO(Bruce): double test and check the log, add restart mongod service if need
  js="\"
 conf=rs.config();
 conf.members[0].priority = 10;
 rs.reconfig(conf)
  \""
  mongo_eval "${js}" "${hu}" "${hop}" "${nu}" "${pri}"

  # Current config
  show_replset_config "${hu}" "$hop" "${nu}" "${pri}"
  pop="Check only one member in replsetm. These nodes are not in it: ${secs[@]}"
  confirm_or_exit "$pop"

  add_nodes_to_existing_replset "${secs[@]}" "${hu}" "$hop" "${nu}" "${pri}" "false"
}

if [[ -z "$@" ]]; then
  echo -e "Call this bash file like\n ./$0 node1 node2 node2 node4 ... noden sshopIP replset-name"
  exit 1
fi

main "$@"
