#!/bin/bash
# "Starting in MongoDB 4.0, you cannot specify --nojournal option or
# storage.journal.enabled:false for replica set members that use the WiredTiger storage engine.
source ./common.sh
main() {
  local node=$1
  local hop=$2
  local replset_name=$3
  local pri=$4

  local pop="
Node: ${node}
sshhop: ${hop}
Replset name: ${replset_name}
Primary: $pri"
  confirm_or_exit "$pop"
  local hu="${sshhop_user_name}"
  local nu="${ec2_user_name}"

  local f="conf_install_mongod.sh"
  local common_lib="common.sh"

  scp -o ProxyCommand="ssh -W %h:%p ${hu}@${hop}" ./${common_lib} ${nu}@${node}:/tmp/
  scp -o ProxyCommand="ssh -W %h:%p ${hu}@${hop}" ./$f ${nu}@${node}:/tmp/
  echo "cd /tmp; ./$f $replset_name" | ssh ${hu}@$hop ssh -o StrictHostKeyChecking=no ${nu}@$node

  # Current config
  show_replset_config @{hu} ${hop} ${nu} ${pri}
  pop="Check: No Arbiter in this replset}"
  confirm_or_exit "$pop"
  # Add Arbiter
  add_nodes_to_existing_replset "$node" "${hu}" "$hop" "${nu}" "${pri}" "true"
}

if [[ -z "$@" ]]; then
  echo -e "Call this bash file like\n ./$0 node_IP sshopIP replset-name primaryIP"
  exit 1
fi

main "$@"
