#!/bin/bash
source ./common.sh
#########################################
# Apply business to each replset node
# Globals:
#   None
# Arguments:
#   ssh hope user
#   ssh hope IP
#   EC2 user
#   EC2 IP
#   replset name
# Returns:
#   None
#########################################
function do_business() {
  local hu="$1"
  local hop="$2"
  local nu="$3"
  local node="$4"
  local replset_name="$5"
  echo "Enalbe logrotation  ${node} of ${replset_name}"

  declare -r f=logrotate-apply-assum-5G-space.sh
  if [[ ! -e ./$f ]]; then
    err "The batch file $f is not exist"
    return 1
  fi

  declare -r common_lib="common.sh"
  declare -r nodes_lib="common_replsets_nodes_ip.sh"
  scp -o ProxyCommand="ssh -W %h:%p ${hu}@${hop}" ./${nodes_lib} ${nu}@${node}:/tmp/
  scp -o ProxyCommand="ssh -W %h:%p ${hu}@${hop}" ./${common_lib} ${nu}@${node}:/tmp/
  scp -o ProxyCommand="ssh -W %h:%p ${hu}@${hop}" ./$f ${nu}@${node}:/tmp/
  echo "cd /tmp; ./$f " | ssh -t ${hu}@$hop ssh -o StrictHostKeyChecking=no ${nu}@$node
}

function main() {
  env_check
  for_each_replst_node "$@"
  sleep 2
  echo -e "\n\n Done, check the replsets status:"
  each_replsets_primary_and_status
}

main "$@"
